defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${oc.env:PROJECT_ROOT}/output_dir/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/epoch/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/step/loss"
  patience: 10
  mode: "min"

model_summary:
  max_depth: -1
